package dev.stevecreate.agent.core.formalbackup;

/** Stable Stage-B fail-closed vocabulary. */
public enum FormalBackupFailureCode {
    BACKUP_SOURCE_WORLD_MISMATCH,
    BACKUP_DESTINATION_UNSAFE,
    BACKUP_DESTINATION_INSIDE_FORMAL_ROOT,
    BACKUP_REPARSE_POINT_FORBIDDEN,
    BACKUP_DISK_SPACE_INSUFFICIENT,
    BACKUP_SOURCE_CHANGED_DURING_COPY,
    BACKUP_COPY_FAILED,
    BACKUP_MANIFEST_INVALID,
    BACKUP_INCOMPLETE,
    BACKUP_VERIFICATION_FAILED,
    BACKUP_ALREADY_EXISTS,
    RESTORE_TARGET_UNSAFE,
    RESTORE_DRILL_FAILED,
    RESTORE_FINGERPRINT_MISMATCH,
    DEPLOYMENT_CANDIDATE_MISSING,
    DEPLOYMENT_CANDIDATE_AMBIGUOUS,
    FORMAL_REGION_NOT_SELECTED,
    APPROVAL_REQUEST_INVALID,
    APPROVAL_DECISION_REQUIRED,
    FORMAL_APPROVAL_NOT_GRANTED,
    FORMAL_RESOURCE_INVENTORY_NOT_AUTHORIZED,
    CLAIM_PERMISSION_UNKNOWN,
    FORMAL_WORLD_EXECUTION_FORBIDDEN
}
