package dev.stevecreate.agent.core.formalbackup;

public enum FormalBackupVerificationCheck {
    TARGET_OUTSIDE_FORMAL_PLATFORM,
    TARGET_INSIDE_REGISTERED_BACKUP_ROOT,
    ORDINARY_NON_REPARSE_TREE,
    COMPLETION_MARKER_CANONICAL,
    COMPLETION_IDENTITY_SELF_VALID,
    MANIFEST_CANONICAL,
    MANIFEST_AGGREGATES_MATCH,
    FILE_TREE_EXACT,
    WORLD_IDENTITY_BOUND,
    PRIVATE_CONTENT_NOT_PARSED,
    FORMAL_SOURCE_NOT_READ_OR_WRITTEN
}
