package dev.stevecreate.agent.core.formalbackup;

public enum FormalRestoreDrillCheck {
    BACKUP_REVERIFIED,
    TARGET_UNDER_REPOSITORY_WORK,
    TARGET_OUTSIDE_FORMAL_PLATFORM,
    NEW_DISPOSABLE_TARGET,
    FILE_COUNT_PATH_SIZE_HASH_EXACT,
    WORLD_IDENTITY_EXACT,
    OFFLINE_LEVEL_DAT_PARSED,
    MINECRAFT_NOT_STARTED,
    FORMAL_SOURCE_NOT_READ_OR_WRITTEN,
    PRIVATE_CONTENT_NOT_PARSED
}
