package dev.stevecreate.agent.core.deployment;

public enum BackupVerificationFailure {
    ENVIRONMENT_NOT_ISOLATED,
    SOURCE_OUTSIDE_ISOLATED_ROOT,
    TARGET_OUTSIDE_BACKUP_ROOT,
    SOURCE_TARGET_COLLISION,
    MANIFEST_INCOMPLETE,
    MANIFEST_HASH_INVALID,
    ESTIMATED_SIZE_MISMATCH,
    INSUFFICIENT_SPACE,
    ATOMICITY_STRATEGY_UNSAFE,
    CONSISTENCY_STRATEGY_UNSAFE,
    RESTORE_DRILL_INCOMPLETE,
    FAILURE_HANDLING_UNSAFE,
    APPROVAL_MISSING,
    JOURNAL_IDENTITY_MISMATCH
}
