package dev.stevecreate.agent.core.deployment;

public enum DeploymentFailureCode {
    WORLD_ENVIRONMENT_UNKNOWN, FORMAL_WORLD_EXECUTION_FORBIDDEN, FORBIDDEN_GAME_DIRECTORY,
    WORLD_IDENTITY_MISMATCH, WORLD_SNAPSHOT_STALE, RUNTIME_FINGERPRINT_MISMATCH,
    DEPLOYMENT_POLICY_MISSING, DEPLOYMENT_POLICY_VIOLATION, DRY_RUN_REQUIRED,
    DEPLOYMENT_PREVIEW_INVALID, PREVIEW_HASH_MISMATCH, REGION_AUTHORIZATION_MISSING,
    REGION_AUTHORIZATION_INSUFFICIENT, CLAIM_PERMISSION_UNKNOWN, CLAIM_PERMISSION_DENIED,
    HUMAN_APPROVAL_REQUIRED, HUMAN_APPROVAL_INVALID, HUMAN_APPROVAL_EXPIRED,
    HUMAN_APPROVAL_ALREADY_USED, HUMAN_APPROVAL_SCOPE_MISMATCH, BACKUP_REQUIRED,
    BACKUP_PLAN_INVALID, BACKUP_FAILED, BACKUP_INCOMPLETE, RESTORE_VERIFICATION_FAILED,
    DISK_SPACE_INSUFFICIENT, RESOURCE_BUDGET_EXCEEDED, MUTATION_BUDGET_EXCEEDED,
    POWER_BUDGET_EXCEEDED, CRITICAL_DEPLOYMENT_RISK, PROTECTED_BLOCK_ENCOUNTERED,
    BLOCK_ENTITY_PROTECTED, UNKNOWN_BLOCK_REPLACEMENT_FORBIDDEN,
    ROLLBACK_POLICY_INSUFFICIENT, WRONG_THREAD, DEPLOYMENT_NOT_READY
}
