package dev.stevecreate.agent.core.deployment;

public enum DeploymentBudgetViolation {
    AFFECTED_BLOCK_LIMIT_EXCEEDED,
    MUTATION_BUDGET_EXCEEDED,
    MATERIAL_BUDGET_EXCEEDED,
    POWER_CAPACITY_INSUFFICIENT,
    STRESS_BUDGET_EXCEEDED,
    POWER_COMPONENT_NOT_IN_BOM,
    LOGISTICS_COMPONENT_NOT_IN_BOM,
    RESOURCE_SOURCE_POLICY_MISMATCH,
    RESOURCE_SOURCE_UNSUPPORTED,
    RESOURCE_SOURCE_NOT_READ_ONLY,
    FORMAL_WORLD_AUTO_WITHDRAW_FORBIDDEN
}
