package dev.stevecreate.agent.core.deployment;

/** Canonical PW-11 deployment gate ordering. */
public enum DeploymentReadinessCheck {
    VERIFIED_PHYSICAL_PLAN_VALID,
    UNIFIED_MACHINE_GRAPH_VALID,
    ENVIRONMENT_CLASSIFICATION_CLEAR,
    DEPLOYMENT_POLICY_PRESENT,
    FORMAL_WORLD_POLICY_NOT_RELAXED,
    DRY_RUN_COMPLETED,
    PREVIEW_HASH_VALID,
    SNAPSHOT_NOT_STALE,
    RUNTIME_FINGERPRINT_UNCHANGED,
    REGION_AUTHORIZATION_COVERS_AFFECTED_REGION,
    OPERATION_PERMISSION_COMPLETE,
    NO_CRITICAL_RISK,
    HIGH_RISK_HANDLED_BY_POLICY,
    BUDGET_WITHIN_LIMIT,
    RESOURCE_SOURCE_LEGAL,
    POWER_CAPACITY_LEGAL,
    BACKUP_REQUIREMENT_SATISFIED,
    BACKUP_MANIFEST_VALID,
    HUMAN_APPROVAL_VALID,
    HUMAN_APPROVAL_NOT_EXPIRED,
    HUMAN_APPROVAL_UNUSED,
    HUMAN_APPROVAL_EXACT_SCOPE,
    ROLLBACK_POLICY_SATISFIED,
    FORMAL_PCL2_HARD_GATED,
    EXECUTION_ENVIRONMENT_ALLOWED
}
