package dev.stevecreate.agent.core.deployment;

public enum DeploymentRiskCategory {
    BLOCK_PLACEMENT_COUNT,
    BLOCK_REMOVAL_COUNT,
    UNKNOWN_BLOCK_REPLACEMENT,
    PLAYER_BUILDING_OVERWRITE,
    BLOCK_ENTITY,
    CONTAINER_CONTENTS,
    FLUID,
    FIRE_OR_LAVA,
    EXPLOSION,
    DROPPED_ENTITY,
    CHUNK_BOUNDARY,
    DIMENSION,
    POWER_OVERLOAD,
    LOGISTICS_CONGESTION,
    RESOURCE_SHORTAGE,
    INCOMPLETE_ROLLBACK,
    RELOAD_RECOVERY,
    MULTI_NODE_RESOURCE_HISTORY,
    CLAIM_PERMISSION_UNKNOWN,
    BACKUP_UNAVAILABLE,
    SNAPSHOT_STALE,
    RUNTIME_FINGERPRINT_CHANGED
}
