package dev.stevecreate.agent.core.deployment;

public enum DeploymentReadinessFailure {
    VERIFIED_PHYSICAL_PLAN_INVALID,
    UNIFIED_MACHINE_GRAPH_INVALID,
    ENVIRONMENT_CLASSIFICATION_UNCLEAR,
    DEPLOYMENT_POLICY_MISSING,
    FORMAL_WORLD_POLICY_RELAXED,
    DRY_RUN_INCOMPLETE,
    PREVIEW_HASH_INVALID,
    WORLD_SNAPSHOT_STALE,
    RUNTIME_FINGERPRINT_CHANGED,
    REGION_AUTHORIZATION_INCOMPLETE,
    OPERATION_PERMISSION_INCOMPLETE,
    CRITICAL_RISK_PRESENT,
    HIGH_RISK_UNHANDLED,
    DEPLOYMENT_BUDGET_EXCEEDED,
    RESOURCE_SOURCE_INVALID,
    POWER_CAPACITY_INVALID,
    BACKUP_REQUIREMENT_UNSATISFIED,
    BACKUP_MANIFEST_INVALID,
    HUMAN_APPROVAL_INVALID,
    HUMAN_APPROVAL_EXPIRED,
    HUMAN_APPROVAL_ALREADY_USED,
    HUMAN_APPROVAL_SCOPE_MISMATCH,
    ROLLBACK_POLICY_UNSATISFIED,
    FORMAL_WORLD_HARD_GATE_MISSING,
    EXECUTION_ENVIRONMENT_NOT_ALLOWED
}
