package dev.stevecreate.agent.core.deployment;

public enum HumanApprovalFailure {
    APPROVAL_NOT_GRANTED,
    APPROVAL_EXPIRED,
    ENVIRONMENT_MISMATCH,
    WORLD_IDENTITY_MISMATCH,
    WORLD_SNAPSHOT_MISMATCH,
    RUNTIME_FINGERPRINT_MISMATCH,
    RELOAD_GENERATION_MISMATCH,
    REGION_MISMATCH,
    TARGET_MISMATCH,
    QUANTITY_MISMATCH,
    MUTATION_BUDGET_MISMATCH,
    DEPLOYMENT_POLICY_MISMATCH,
    PREVIEW_HASH_MISMATCH,
    TEST_ONLY_SCOPE_FORBIDDEN,
    TOKEN_ALREADY_CONSUMED
}
