package dev.stevecreate.agent.core.deployment;

public enum RegionAuthorizationFailure {
    ENVIRONMENT_MISMATCH,
    WORLD_IDENTITY_MISMATCH,
    DIMENSION_MISMATCH,
    OWNER_IDENTITY_MISMATCH,
    REGION_OUT_OF_SCOPE,
    OPERATION_NOT_ALLOWED,
    MUTATION_BUDGET_EXCEEDED,
    PREVIEW_HASH_MISMATCH,
    WORLD_SNAPSHOT_MISMATCH,
    RUNTIME_FINGERPRINT_MISMATCH,
    EXPIRED,
    NOT_APPROVED,
    REVOKED,
    ONE_TIME_USE_ALREADY_CONSUMED,
    FORMAL_WORLD_EXECUTION_FORBIDDEN
}
