package dev.stevecreate.agent.core.deployment;

/** Stable IWP refusal vocabulary. New pilot code must fail through one of these values. */
public enum WritableTestWorldFailureCode {
    TEST_INSTANCE_NOT_FOUND,
    TEST_WORLD_NOT_FOUND,
    MULTIPLE_TEST_WORLDS_AMBIGUOUS,
    TEST_WORLD_IDENTITY_MISMATCH,
    FORMAL_WORLD_FORBIDDEN,
    TEST_WORLD_IN_USE_DURING_BACKUP,
    TEST_WORLD_BACKUP_REQUIRED,
    TEST_WORLD_BACKUP_INVALID,
    TEST_WORLD_FINGERPRINT_STALE,
    REGION_NOT_SELECTED,
    REGION_NOT_CONFIRMED,
    REGION_TOO_LARGE,
    REGION_DIMENSION_MISMATCH,
    REGION_HASH_STALE,
    REGION_CONTAINS_PROTECTED_BLOCK,
    REGION_CONTAINS_IMPORTANT_BLOCK_ENTITY,
    REGION_INSUFFICIENT_SPACE,
    PILOT_PREVIEW_REQUIRED,
    PILOT_PREVIEW_STALE,
    PILOT_TARGET_UNSUPPORTED,
    PILOT_MATERIAL_SOURCE_UNAVAILABLE,
    PILOT_POWER_SOURCE_UNAVAILABLE,
    PILOT_DUPLICATE_SESSION,
    PILOT_CANCELLED,
    PILOT_CLEANUP_UNSAFE,
    PILOT_RECOVERY_UNSAFE,
    TEST_ONLY_CAPABILITY_FORBIDDEN_IN_FORMAL_WORLD,
    FORMAL_WORLD_EXECUTION_FORBIDDEN
}
