package dev.stevecreate.agent.adapter.api;

public enum AdapterFailureCode {
    UNSUPPORTED_RUNTIME,
    WRONG_THREAD,
    LIFECYCLE_NOT_READY,
    CHUNK_NOT_LOADED,
    SCAN_LIMIT_EXCEEDED,
    KINETIC_COMPONENT_NOT_FOUND,
    CREATE_API_FAILURE,
    INDUSTRIAL_API_FAILURE,
    MULTIBLOCK_NOT_FOUND,
    NETWORK_NOT_FOUND,
    ACTION_REFUSED,
    PLAN_REJECTED,
    PLACEMENT_FAILED,
    RECIPE_NOT_FOUND,
    PROCESSING_FAILED,
    EXECUTION_TIMEOUT,
    SNAPSHOT_EXPIRED,
    FORMAL_WORLD_EXECUTION_FORBIDDEN
}
