package dev.stevecreate.agent.adapter.api;

/** Stable typed failures for runtime recipe/capability discovery and read-only planning. */
public enum RuntimeKnowledgeFailureCode {
    RUNTIME_RECIPE_MANAGER_UNAVAILABLE,
    RECIPE_TYPE_UNSUPPORTED,
    INGREDIENT_UNSUPPORTED,
    INGREDIENT_CHOICE_UNRESOLVED,
    OUTPUT_UNSUPPORTED,
    RECIPE_MAPPING_FAILED,
    RUNTIME_FINGERPRINT_MISMATCH,
    RECIPE_CATALOG_STALE,
    CAPABILITY_CATALOG_MISSING,
    REQUIRED_MOD_UNAVAILABLE,
    RECIPE_NOT_FOUND,
    MACHINE_CAPABILITY_MISSING,
    QUANTITY_CONVERSION_INVALID,
    DATAPACK_RELOAD_IN_PROGRESS,
    WRONG_THREAD,
    WORLD_NOT_AVAILABLE
}
