package dev.stevecreate.agent.core.execution.readiness;

/** Stable typed refusal contract shared by readiness and goal-driven execution. */
public enum ExecutionReadinessFailureCode {
    EXECUTION_NOT_READY,
    PHYSICAL_PLAN_STALE,
    TARGET_AREA_CHANGED,
    REQUIRED_CHUNK_UNLOADED,
    INPUT_RESOURCE_MISSING,
    POWER_SOURCE_MISSING,
    STRESS_CAPACITY_INSUFFICIENT,
    BLOCK_PLACEMENT_BLOCKED,
    ROUTE_CONSTRUCTION_FAILED,
    SESSION_ALREADY_EXISTS,
    JOURNAL_UNAVAILABLE,
    RELOAD_RECOVERY_UNSAFE,
    PROCESS_TIMEOUT,
    INPUT_NOT_CONSUMED,
    OUTPUT_NOT_PRODUCED,
    OUTPUT_QUANTITY_MISMATCH,
    VERIFICATION_EVIDENCE_MISSING,
    ROLLBACK_UNSAFE,
    EXECUTION_CANCELLED,
    FORMAL_WORLD_FORBIDDEN
}
