package dev.stevecreate.agent.core.execution.readiness;

public enum ExecutionReadinessVerificationCheck {
    PHYSICAL_PLAN_VERIFIED,
    RUNTIME_FINGERPRINT_MATCHES,
    IMPLEMENTATION_AND_ADAPTER_AVAILABLE,
    AUTHORITATIVE_WORLD_THREAD,
    REQUIRED_CHUNKS_LOADED,
    TARGET_AREA_UNCHANGED,
    FOOTPRINT_AND_CLEARANCE_VALID,
    ITEM_AND_POWER_ROUTES_VALID,
    INPUT_RESOURCES_AVAILABLE,
    POWER_AND_STRESS_AVAILABLE,
    CONSTRUCTION_BUDGET_BOUNDED,
    ROLLBACK_BOUNDARY_SAFE,
    JOURNAL_WRITABLE,
    RELOAD_RECOVERY_SAFE,
    SESSION_ID_UNIQUE,
    FORMAL_WORLD_EXCLUDED
}
