package dev.stevecreate.agent.core.siteprep;

public enum SitePreparationFailureCode {
    SITE_ANCHOR_NOT_SELECTED,
    SITE_REGION_NOT_SELECTED,
    SITE_FACING_NOT_SELECTED,
    SITE_SELECTION_STALE,
    SITE_WORLD_MISMATCH,
    SITE_DIMENSION_MISMATCH,
    SITE_OUTSIDE_AUTHORIZED_REGION,
    SITE_SURVEY_REQUIRED,
    SITE_SURVEY_STALE,
    OBSTACLE_CLASSIFICATION_UNKNOWN,
    PROTECTED_OBSTACLE_PRESENT,
    DEMOLITION_APPROVAL_REQUIRED,
    DEMOLITION_APPROVAL_STALE,
    DEMOLITION_APPROVAL_SCOPE_MISMATCH,
    DEMOLITION_APPROVAL_EXPIRED,
    DEMOLITION_BUDGET_EXCEEDED,
    BOT_CLEARING_PATH_UNREACHABLE,
    BOT_CLEARING_TOOL_UNAVAILABLE,
    SALVAGE_DESTINATION_UNAVAILABLE,
    TERRAIN_LEVELING_UNSAFE,
    ENVIRONMENTAL_HAZARD_PRESENT,
    POST_CLEARANCE_RESCAN_REQUIRED,
    POST_CLEARANCE_SITE_CHANGED,
    PREPARED_SITE_STALE,
    FORMAL_WORLD_SITE_PREPARATION_FORBIDDEN
}
