package dev.stevecreate.agent.core.binding;

/** Stable typed failures for implementation binding and its explicit layout boundary. */
public enum BindingFailureCode {
    IMPLEMENTATION_CATALOG_MISSING,
    IMPLEMENTATION_NOT_FOUND,
    IMPLEMENTATION_CAPABILITY_MISMATCH,
    IMPLEMENTATION_RECIPE_TYPE_MISMATCH,
    IMPLEMENTATION_ADAPTER_UNAVAILABLE,
    IMPLEMENTATION_MOD_UNAVAILABLE,
    IMPLEMENTATION_RUNTIME_MISMATCH,
    IMPLEMENTATION_PORT_CONTRACT_INVALID,
    IMPLEMENTATION_POWER_CONTRACT_INVALID,
    IMPLEMENTATION_EXECUTION_UNVERIFIED,
    IMPLEMENTATION_FORBIDDEN,
    MULTIPLE_IMPLEMENTATIONS_AMBIGUOUS,
    LOGICAL_NODE_UNBOUND,
    BINDING_GRAPH_INVALID,
    BINDING_NOT_LAYOUT_READY,
    PHYSICAL_PORTS_NOT_RESOLVED,
    LAYOUT_REQUIRED,
    IMPLEMENTATION_RELOAD_IN_PROGRESS,
    WRONG_THREAD,
    WORLD_CONTEXT_NOT_REQUIRED
}
