package dev.stevecreate.agent.core.layout;

/** Exhaustive typed failures for implementation-bound physicalization. */
public enum LayoutFailureCode {
    LAYOUT_CONSTRAINTS_MISSING,
    FOOTPRINT_UNAVAILABLE,
    CLEARANCE_BLOCKED,
    ORIENTATION_UNAVAILABLE,
    PHYSICAL_PORT_RESOLUTION_FAILED,
    ITEM_ROUTE_NOT_FOUND,
    ROTATIONAL_POWER_ROUTE_NOT_FOUND,
    ROUTE_CAPACITY_INSUFFICIENT,
    STRESS_CAPACITY_INSUFFICIENT,
    PLACEMENT_COLLISION,
    SEARCH_BUDGET_EXHAUSTED,
    PHYSICALIZATION_FAILED,
    UNIFIED_GRAPH_INVALID,
    WORLD_SNAPSHOT_STALE,
    UNSUPPORTED_IMPLEMENTATION_GEOMETRY
}
