package dev.stevecreate.agent.core.layout;

public enum PhysicalizationVerificationCheck {
    BINDING_IDENTITY_PRESERVED,
    RUNTIME_SNAPSHOT_MATCHES,
    ORIENTATIONS_SUPPORTED,
    FOOTPRINTS_COLLISION_FREE,
    CLEARANCES_FREE,
    PHYSICAL_PORTS_COMPLETE,
    ITEM_ROUTES_CONNECTED,
    POWER_ROUTES_CONNECTED,
    ROUTE_CAPACITY_SUFFICIENT,
    STRESS_CAPACITY_SUFFICIENT,
    UNIFIED_GRAPH_STRICT,
    SEARCH_BOUNDS_RESPECTED,
    NO_EXECUTION_AUTHORITY
}
