#!/usr/bin/env bash
# A player-acceptance client whose game directory is outside the repository.
#
# The runtime refuses to build in a world whose game directory has a git ancestor
# (SOURCE_TREE_GAME_DIR_REFUSED), and that refusal is right: construction writes region
# files and a source tree is the last place they belong. So the default run directory can
# start a client and can never build in one, which is why the log-layer check is all it
# is good for.
#
# The refusal is about where the directory is. Moving it outside the repository satisfies
# the gate with nothing weakened, and needs no Minecraft licence — ForgeGradle supplies a
# development account, which is why this works where a launcher instance does not.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
game_root="${STEVE_ACCEPTANCE_ROOT:-${HOME}/SteveAgentPlayerAcceptance}"
backup_root="${game_root}-backups"
# Non-empty by contract: IMPORTANT_INSTANCE_ROOT_REQUIRED refuses a configuration that
# names nothing to protect. It must also exist, and must not contain the game directory.
important_root="${STEVE_IMPORTANT_ROOT:-${HOME}/SteveAgentProtectedInstances}"
world_name="Steve Agent Mac Acceptance"

case "${game_root}" in
    "${root}"|"${root}"/*)
        echo "Refusing a game directory inside the repository: ${game_root}" >&2
        echo "The runtime would refuse it with SOURCE_TREE_GAME_DIR_REFUSED." >&2
        exit 1
        ;;
esac

mkdir -p "${game_root}/config" "${game_root}/saves" "${backup_root}" "${important_root}"

printf '%s\n' '# Player-acceptance client, outside the repository. Disposable.' 'eula=true' \
    > "${game_root}/eula.txt"

# Written every run: the game directory is what the runtime compares testInstanceRoot
# against, so a stale path here reads as TEST_INSTANCE_ROOT_MISMATCH and says nothing
# about what actually differs.
cat > "${game_root}/config/steve-industrial-agent-common.toml" <<TOML
# Generated by scripts/new-player-acceptance-client.sh. Disposable.
[runtime]
configSchemaVersion = 1
runtimeMode = "DISPOSABLE_TEST_WORLD"
testInstanceRoot = "${game_root}"
allowedTestWorlds = ["${world_name}"]
backupRoot = "${backup_root}"
importantInstanceRoots = ["${important_root}"]
maxRegionSize = 32
requireBackup = true
requireWorldMarker = true
allowDirectPilot = true
diagnosticsRedaction = true
formalWorldPolicy = "DENY_CONFIGURED_ROOTS"
TOML

echo "Game directory : ${game_root}"
echo "Backups        : ${backup_root}"
echo "Protected root : ${important_root}"
echo "World to create: ${world_name}  (creative, cheats on)"
echo
echo "Starting the client. Create that world by that exact name, then run:"
echo "  /industrialagent setup show-config"
echo "  /industrialagent setup mark-test-world"
echo "  /industrialagent setup validate"
echo

export JAVA_HOME="${JAVA_HOME:-$(/usr/libexec/java_home -v 17)}"
acceptance_harness_args=()
if [[ "${STEVE_ACCEPTANCE_HARNESS:-0}" == "1" ]]; then
    token_file="${STEVE_ACCEPTANCE_TOKEN_FILE:-}"
    endpoint="${STEVE_ACCEPTANCE_ENDPOINT:-}"
    port="${STEVE_ACCEPTANCE_PORT:-0}"
    quick_play_world="${STEVE_ACCEPTANCE_QUICK_PLAY_WORLD:-}"
    if [[ "${token_file}" != "${game_root}/.steve-agent-harness/bridge-token" \
          || ! -f "${token_file}" || -L "${token_file}" ]]; then
        echo "Refusing an invalid acceptance-harness token file." >&2
        exit 2
    fi
    token_mode="$(stat -f '%Lp' "${token_file}" 2>/dev/null || stat -c '%a' "${token_file}")"
    if [[ "${token_mode}" != "600" ]]; then
        echo "Refusing an acceptance-harness token file not locked to mode 600." >&2
        exit 2
    fi
    if [[ "${endpoint}" != "${game_root}/.steve-agent-harness/bridge.json" ]]; then
        echo "Refusing an acceptance endpoint outside the disposable game root." >&2
        exit 2
    fi
    if [[ -n "${quick_play_world}" && "${quick_play_world}" != "${world_name}" ]]; then
        echo "Refusing a quick-play world other than: ${world_name}" >&2
        exit 2
    fi
    mkdir -p "${game_root}/.steve-agent-harness"
    acceptance_harness_args+=(
        -PclientAcceptanceHarness=true
        "-PclientAcceptanceHarnessTokenFile=${token_file}"
        "-PclientAcceptanceHarnessEndpoint=${endpoint}"
        "-PclientAcceptanceHarnessPort=${port}"
        "-PclientAcceptanceHarnessWorld=${world_name}"
    )
    if [[ -n "${quick_play_world}" ]]; then
        acceptance_harness_args+=("-PclientAcceptanceQuickPlayWorld=${quick_play_world}")
    fi
    echo "Client harness : enabled (localhost, disposable world only)"
fi
exec "${root}/gradlew" -p "${root}" \
    -PincludeImmersiveEngineeringRuntime=true \
    -PplayerAcceptanceRoot="${game_root}" \
    "${acceptance_harness_args[@]}" \
    :forge-create-1.20.1:runClient --console=plain
