package dev.stevecreate.agent.core.survey;

/** Stable fail-closed vocabulary for formal-world survey and backup preparation. */
public enum FormalSurveyFailureCode {
    FORMAL_SAVE_ROOT_NOT_FOUND,
    MULTIPLE_FORMAL_WORLDS_AMBIGUOUS,
    FORMAL_WORLD_NOT_SELECTED,
    FORMAL_WORLD_PATH_OUTSIDE_ALLOWED_ROOT,
    FORMAL_WORLD_REPARSE_POINT_FORBIDDEN,
    FORMAL_WORLD_WRITE_ATTEMPT,
    FORMAL_WORLD_LOCK_ATTEMPT,
    FORMAL_WORLD_PROCESS_START_FORBIDDEN,
    LEVEL_DAT_UNREADABLE,
    WORLD_DATA_VERSION_UNSUPPORTED,
    REGION_HEADER_INVALID,
    REGION_CHUNK_OFFSET_INVALID,
    CHUNK_COMPRESSION_UNSUPPORTED,
    CHUNK_NBT_TOO_LARGE,
    CHUNK_NBT_CORRUPT,
    SURVEY_BUDGET_EXHAUSTED,
    SURVEY_PARTIAL,
    BLOCK_PALETTE_UNSUPPORTED,
    BLOCK_ENTITY_UNSUPPORTED,
    CREATE_INFRASTRUCTURE_NOT_FOUND,
    CANDIDATE_ZONE_NOT_FOUND,
    CLAIM_PERMISSION_UNKNOWN,
    FORMAL_INVENTORY_CONTENTS_FORBIDDEN,
    WORLD_FINGERPRINT_CHANGED_DURING_SURVEY,
    EXTERNAL_MUTATION_DETECTED,
    FORMAL_WORLD_DRY_RUN_ONLY,
    FORMAL_WORLD_EXECUTION_FORBIDDEN
}
