package dev.stevecreate.agent.adapter.api.create;

/** Stable typed limitations for C-05 through C-10 recipe semantics. */
public enum CapabilityRecipeLimitationCode {
    RECIPE_CLASS_UNSUPPORTED,
    ITEM_INGREDIENT_UNSUPPORTED,
    FLUID_INPUT_PHASE_I_UNSUPPORTED,
    FLUID_OUTPUT_PHASE_I_UNSUPPORTED,
    SUPERHEATED_PHASE_I_UNSUPPORTED,
    UNKNOWN_HEAT,
    PRIMARY_OUTPUT_PROBABILISTIC,
    OUTPUT_NBT_UNSUPPORTED,
    OUTPUT_MISSING,
    COMPLEX_REMAINDER_UNSUPPORTED,
    HELD_ITEM_NOT_EXACT,
    HELD_ITEM_STATE_UNKNOWN,
    UNKNOWN_SIDE_EFFECT,
    RUNTIME_REQUIREMENT_UNAVAILABLE
}
